name: Build Mock Server
on:
  push:
    branches: [ main, 'feature/**' ]
    paths: [ 'server-mock/**', 'workflows/build_mock_server.yml' ]

env:
  GAR_LOCATION: ${{vars.MOCK_SERVER_ARTIFACT_NAME}}:latest

jobs:
  build:
    name: Build Mock Server Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        working-directory: server-mock/
        run: docker build --build-arg SELF_SIGNED_CERT_PASSWORD=${{secrets.SELF_SIGNED_CERT_PASSWORD}} -t ${{ env.GAR_LOCATION }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ env.GAR_LOCATION }}
  deploy:
    needs: build
    name: Deploy Mock Server
    runs-on: ubuntu-latest
    steps:
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Deploy latest
        run: |
          docker pull ${{ env.GAR_LOCATION }}
          gcloud compute instances update-container server-mock --container-image ${{env.GAR_LOCATION}} \
            --zone us-east1-c --container-env CORS_ALLOWED_URL=https://test-domain-promise.online/