name: Build Flutter Web
on:
  push:
    branches: [ main, 'feature/**' ]
    paths: [ 'frontend/**' ]

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build Flutter Web
        working-directory: frontend/
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Deploy latest to Cloud Storage
        working-directory: frontend/
        run: |
          gcloud config set project ${{vars.GCP_PROJECT}}
          gcloud storage cp -r build/web/* gs://${{vars.GCP_STORAGE_FRONTEND}}
